---
- name: install the latest of package related to pyenv
  become: yes
  yum: name={{ item }} state=latest
  with_items:
  - patch
  - readline-devel
  - zlib-devel
  - bzip2-devel
  - sqlite-devel
  - openssl-devel
  - git
  - libffi-devel

- name: install pyenv
  git: repo=https://github.com/yyuu/pyenv.git dest=~/.pyenv

- name: install pyenv-virtualenv
  git: repo=https://github.com/yyuu/pyenv-virtualenv.git dest=~/.pyenv/plugins/pyenv-virtualenv

- name: set env-val to ~/.bash_profile
  shell: |
    (
      echo 'export PYENV_ROOT="$HOME/.pyenv"'
      echo 'export PATH="$PYENV_ROOT/bin:$PATH"'
      echo 'eval "$(pyenv init -)"'
      echo 'eval "$(pyenv virtualenv-init -)"'
    ) >> ~/.bash_profile
    source ~/.bash_profile

- name: install python into pyenv and create virtualenvs
  shell: |
    ~/.pyenv/bin/pyenv install 2.7.10
    ~/.pyenv/bin/pyenv virtualenv 2.7.10 ansible1
    ~/.pyenv/bin/pyenv virtualenv 2.7.10 ansible2

- name: install latest ansible into ansible2-env
  pip: name=ansible virtualenv=~/.pyenv/versions/ansible2

- name: install ansible1.x into ansible1-env
  pip: name=ansible version=1.6.6 virtualenv=~/.pyenv/versions/ansible1
